// Generated by: supabase gen types typescript (project pippmbrzwjcwbhmvbveg)
// Regenerate with: supabase gen types typescript --linked > packages/types/src/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          actor_user_id: string | null
          after_data: Json | null
          before_data: Json | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          ip_hash: string | null
          organization_id: string | null
          request_id: string | null
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          after_data?: Json | null
          before_data?: Json | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          ip_hash?: string | null
          organization_id?: string | null
          request_id?: string | null
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          after_data?: Json | null
          before_data?: Json | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          ip_hash?: string | null
          organization_id?: string | null
          request_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_logs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      brands: {
        Row: {
          active: boolean
          created_at: string
          id: string
          logo_path: string | null
          name: string
          organization_id: string
          slug: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          logo_path?: string | null
          name: string
          organization_id: string
          slug: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          logo_path?: string | null
          name?: string
          organization_id?: string
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "brands_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_items: {
        Row: {
          cart_id: string
          created_at: string
          id: string
          quantity: number
          updated_at: string
          variant_id: string
        }
        Insert: {
          cart_id: string
          created_at?: string
          id?: string
          quantity: number
          updated_at?: string
          variant_id: string
        }
        Update: {
          cart_id?: string
          created_at?: string
          id?: string
          quantity?: number
          updated_at?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_items_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: false
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      carts: {
        Row: {
          anonymous_token: string | null
          created_at: string
          currency: string
          customer_id: string | null
          expires_at: string | null
          id: string
          organization_id: string
          status: string
          updated_at: string
          version: number
        }
        Insert: {
          anonymous_token?: string | null
          created_at?: string
          currency?: string
          customer_id?: string | null
          expires_at?: string | null
          id?: string
          organization_id: string
          status?: string
          updated_at?: string
          version?: number
        }
        Update: {
          anonymous_token?: string | null
          created_at?: string
          currency?: string
          customer_id?: string | null
          expires_at?: string | null
          id?: string
          organization_id?: string
          status?: string
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "carts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "carts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          active: boolean
          created_at: string
          description: string | null
          id: string
          image_path: string | null
          name: string
          organization_id: string
          parent_id: string | null
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          description?: string | null
          id?: string
          image_path?: string | null
          name: string
          organization_id: string
          parent_id?: string | null
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          description?: string | null
          id?: string
          image_path?: string | null
          name?: string
          organization_id?: string
          parent_id?: string | null
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      consent_logs: {
        Row: {
          consent_type: string
          created_at: string
          customer_id: string | null
          granted: boolean
          id: string
          ip_hash: string | null
          source: string | null
          user_agent: string | null
          user_id: string | null
          version: string
        }
        Insert: {
          consent_type: string
          created_at?: string
          customer_id?: string | null
          granted: boolean
          id?: string
          ip_hash?: string | null
          source?: string | null
          user_agent?: string | null
          user_id?: string | null
          version: string
        }
        Update: {
          consent_type?: string
          created_at?: string
          customer_id?: string | null
          granted?: boolean
          id?: string
          ip_hash?: string | null
          source?: string | null
          user_agent?: string | null
          user_id?: string | null
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "consent_logs_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      coupons: {
        Row: {
          active: boolean
          code: string
          created_at: string
          discount_type: string
          discount_value: number
          expires_at: string | null
          id: string
          max_uses: number | null
          min_order_cents: number
          organization_id: string
          partner_id: string | null
          starts_at: string | null
          updated_at: string
          used_count: number
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          discount_type: string
          discount_value: number
          expires_at?: string | null
          id?: string
          max_uses?: number | null
          min_order_cents?: number
          organization_id: string
          partner_id?: string | null
          starts_at?: string | null
          updated_at?: string
          used_count?: number
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          discount_type?: string
          discount_value?: number
          expires_at?: string | null
          id?: string
          max_uses?: number | null
          min_order_cents?: number
          organization_id?: string
          partner_id?: string | null
          starts_at?: string | null
          updated_at?: string
          used_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "coupons_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coupons_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_addresses: {
        Row: {
          city: string
          complement: string | null
          country: string
          created_at: string
          customer_id: string
          district: string | null
          id: string
          is_default: boolean
          label: string | null
          number: string
          postal_code: string
          recipient_name: string
          state: string
          street: string
          updated_at: string
        }
        Insert: {
          city: string
          complement?: string | null
          country?: string
          created_at?: string
          customer_id: string
          district?: string | null
          id?: string
          is_default?: boolean
          label?: string | null
          number: string
          postal_code: string
          recipient_name: string
          state: string
          street: string
          updated_at?: string
        }
        Update: {
          city?: string
          complement?: string | null
          country?: string
          created_at?: string
          customer_id?: string
          district?: string | null
          id?: string
          is_default?: boolean
          label?: string | null
          number?: string
          postal_code?: string
          recipient_name?: string
          state?: string
          street?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_addresses_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string
          email: string
          full_name: string
          id: string
          organization_id: string
          phone: string | null
          source: string
          status: string
          tax_id_encrypted: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          full_name: string
          id?: string
          organization_id: string
          phone?: string | null
          source?: string
          status?: string
          tax_id_encrypted?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          organization_id?: string
          phone?: string | null
          source?: string
          status?: string
          tax_id_encrypted?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      fiscal_documents: {
        Row: {
          access_key: string | null
          authorized_at: string | null
          cancelled_at: string | null
          created_at: string
          document_type: string
          external_id: string | null
          id: string
          idempotency_key: string
          issued_at: string | null
          number: string | null
          order_id: string | null
          organization_id: string
          pdf_storage_path: string | null
          protocol: string | null
          rejection_code: string | null
          rejection_message: string | null
          series: string | null
          status: string
          updated_at: string
          xml_storage_path: string | null
        }
        Insert: {
          access_key?: string | null
          authorized_at?: string | null
          cancelled_at?: string | null
          created_at?: string
          document_type: string
          external_id?: string | null
          id?: string
          idempotency_key: string
          issued_at?: string | null
          number?: string | null
          order_id?: string | null
          organization_id: string
          pdf_storage_path?: string | null
          protocol?: string | null
          rejection_code?: string | null
          rejection_message?: string | null
          series?: string | null
          status?: string
          updated_at?: string
          xml_storage_path?: string | null
        }
        Update: {
          access_key?: string | null
          authorized_at?: string | null
          cancelled_at?: string | null
          created_at?: string
          document_type?: string
          external_id?: string | null
          id?: string
          idempotency_key?: string
          issued_at?: string | null
          number?: string | null
          order_id?: string | null
          organization_id?: string
          pdf_storage_path?: string | null
          protocol?: string | null
          rejection_code?: string | null
          rejection_message?: string | null
          series?: string | null
          status?: string
          updated_at?: string
          xml_storage_path?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fiscal_documents_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fiscal_documents_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      goods_receipts: {
        Row: {
          created_at: string
          id: string
          notes: string | null
          organization_id: string
          purchase_order_id: string | null
          receipt_number: string
          received_at: string | null
          received_by: string | null
          status: string
          updated_at: string
          warehouse_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          notes?: string | null
          organization_id: string
          purchase_order_id?: string | null
          receipt_number: string
          received_at?: string | null
          received_by?: string | null
          status?: string
          updated_at?: string
          warehouse_id: string
        }
        Update: {
          created_at?: string
          id?: string
          notes?: string | null
          organization_id?: string
          purchase_order_id?: string | null
          receipt_number?: string
          received_at?: string | null
          received_by?: string | null
          status?: string
          updated_at?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "goods_receipts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_received_by_fkey"
            columns: ["received_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      incoming_invoices: {
        Row: {
          access_key: string
          created_at: string
          goods_receipt_id: string | null
          id: string
          invoice_number: string | null
          issued_at: string | null
          organization_id: string
          raw_summary: Json | null
          series: string | null
          status: string
          supplier_id: string | null
          total_cents: number | null
          xml_storage_path: string
        }
        Insert: {
          access_key: string
          created_at?: string
          goods_receipt_id?: string | null
          id?: string
          invoice_number?: string | null
          issued_at?: string | null
          organization_id: string
          raw_summary?: Json | null
          series?: string | null
          status?: string
          supplier_id?: string | null
          total_cents?: number | null
          xml_storage_path: string
        }
        Update: {
          access_key?: string
          created_at?: string
          goods_receipt_id?: string | null
          id?: string
          invoice_number?: string | null
          issued_at?: string | null
          organization_id?: string
          raw_summary?: Json | null
          series?: string | null
          status?: string
          supplier_id?: string | null
          total_cents?: number | null
          xml_storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "incoming_invoices_goods_receipt_id_fkey"
            columns: ["goods_receipt_id"]
            isOneToOne: false
            referencedRelation: "goods_receipts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incoming_invoices_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incoming_invoices_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_balances: {
        Row: {
          on_hand: number
          reserved: number
          updated_at: string
          variant_id: string
          warehouse_id: string
        }
        Insert: {
          on_hand?: number
          reserved?: number
          updated_at?: string
          variant_id: string
          warehouse_id: string
        }
        Update: {
          on_hand?: number
          reserved?: number
          updated_at?: string
          variant_id?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_balances_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_balances_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_movements: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          movement_type: string
          organization_id: string
          quantity: number
          reason: string | null
          reference_id: string | null
          reference_type: string | null
          variant_id: string
          warehouse_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          movement_type: string
          organization_id: string
          quantity: number
          reason?: string | null
          reference_id?: string | null
          reference_type?: string | null
          variant_id: string
          warehouse_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          movement_type?: string
          organization_id?: string
          quantity?: number
          reason?: string | null
          reference_id?: string | null
          reference_type?: string | null
          variant_id?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_movements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_reservations: {
        Row: {
          cart_id: string | null
          created_at: string
          expires_at: string | null
          id: string
          order_id: string | null
          organization_id: string
          quantity: number
          status: string
          updated_at: string
          variant_id: string
          warehouse_id: string
        }
        Insert: {
          cart_id?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          order_id?: string | null
          organization_id: string
          quantity: number
          status?: string
          updated_at?: string
          variant_id: string
          warehouse_id: string
        }
        Update: {
          cart_id?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          order_id?: string | null
          organization_id?: string
          quantity?: number
          status?: string
          updated_at?: string
          variant_id?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_reservations_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_reservations_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_reservations_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      job_queue: {
        Row: {
          attempts: number
          created_at: string
          id: string
          job_type: string
          last_error: string | null
          locked_at: string | null
          locked_by: string | null
          max_attempts: number
          payload: Json
          priority: number
          run_after: string
          status: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          id?: string
          job_type: string
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          max_attempts?: number
          payload: Json
          priority?: number
          run_after?: string
          status?: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          id?: string
          job_type?: string
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          max_attempts?: number
          payload?: Json
          priority?: number
          run_after?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      notification_deliveries: {
        Row: {
          event_type: string | null
          external_id: string | null
          id: string
          job_id: string
          metadata: Json | null
          occurred_at: string
          provider: string
          status: string
        }
        Insert: {
          event_type?: string | null
          external_id?: string | null
          id?: string
          job_id: string
          metadata?: Json | null
          occurred_at?: string
          provider: string
          status: string
        }
        Update: {
          event_type?: string | null
          external_id?: string | null
          id?: string
          job_id?: string
          metadata?: Json | null
          occurred_at?: string
          provider?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_deliveries_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "notification_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_jobs: {
        Row: {
          attempts: number
          channel: string
          created_at: string
          id: string
          last_error: string | null
          organization_id: string | null
          payload: Json
          recipient: string
          run_after: string
          status: string
          template_code: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          channel: string
          created_at?: string
          id?: string
          last_error?: string | null
          organization_id?: string | null
          payload: Json
          recipient: string
          run_after?: string
          status?: string
          template_code: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          channel?: string
          created_at?: string
          id?: string
          last_error?: string | null
          organization_id?: string | null
          payload?: Json
          recipient?: string
          run_after?: string
          status?: string
          template_code?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_jobs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          cost_cents: number | null
          created_at: string
          discount_cents: number
          fiscal_snapshot: Json | null
          id: string
          order_id: string
          product_name: string
          quantity: number
          sku: string
          tax_cents: number
          total_cents: number
          unit_price_cents: number
          variant_id: string | null
          variant_name: string | null
        }
        Insert: {
          cost_cents?: number | null
          created_at?: string
          discount_cents?: number
          fiscal_snapshot?: Json | null
          id?: string
          order_id: string
          product_name: string
          quantity: number
          sku: string
          tax_cents?: number
          total_cents: number
          unit_price_cents: number
          variant_id?: string | null
          variant_name?: string | null
        }
        Update: {
          cost_cents?: number | null
          created_at?: string
          discount_cents?: number
          fiscal_snapshot?: Json | null
          id?: string
          order_id?: string
          product_name?: string
          quantity?: number
          sku?: string
          tax_cents?: number
          total_cents?: number
          unit_price_cents?: number
          variant_id?: string | null
          variant_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      order_status_history: {
        Row: {
          actor_user_id: string | null
          created_at: string
          from_status: string | null
          id: string
          metadata: Json | null
          order_id: string
          reason: string | null
          to_status: string
        }
        Insert: {
          actor_user_id?: string | null
          created_at?: string
          from_status?: string | null
          id?: string
          metadata?: Json | null
          order_id: string
          reason?: string | null
          to_status: string
        }
        Update: {
          actor_user_id?: string | null
          created_at?: string
          from_status?: string | null
          id?: string
          metadata?: Json | null
          order_id?: string
          reason?: string | null
          to_status?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_status_history_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_status_history_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          billing_address: Json | null
          cancelled_at: string | null
          cart_id: string | null
          channel: string
          coupon_snapshot: Json | null
          created_at: string
          currency: string
          customer_id: string | null
          customer_snapshot: Json
          discount_cents: number
          id: string
          order_number: string
          organization_id: string
          paid_at: string | null
          partner_id: string | null
          shipping_address: Json
          shipping_cents: number
          shipping_method_snapshot: Json | null
          status: string
          subtotal_cents: number
          tax_cents: number
          total_cents: number
          updated_at: string
        }
        Insert: {
          billing_address?: Json | null
          cancelled_at?: string | null
          cart_id?: string | null
          channel?: string
          coupon_snapshot?: Json | null
          created_at?: string
          currency?: string
          customer_id?: string | null
          customer_snapshot: Json
          discount_cents?: number
          id?: string
          order_number: string
          organization_id: string
          paid_at?: string | null
          partner_id?: string | null
          shipping_address: Json
          shipping_cents?: number
          shipping_method_snapshot?: Json | null
          status?: string
          subtotal_cents?: number
          tax_cents?: number
          total_cents?: number
          updated_at?: string
        }
        Update: {
          billing_address?: Json | null
          cancelled_at?: string | null
          cart_id?: string | null
          channel?: string
          coupon_snapshot?: Json | null
          created_at?: string
          currency?: string
          customer_id?: string | null
          customer_snapshot?: Json
          discount_cents?: number
          id?: string
          order_number?: string
          organization_id?: string
          paid_at?: string | null
          partner_id?: string | null
          shipping_address?: Json
          shipping_cents?: number
          shipping_method_snapshot?: Json | null
          status?: string
          subtotal_cents?: number
          tax_cents?: number
          total_cents?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: false
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_units: {
        Row: {
          active: boolean
          address: Json | null
          code: string
          created_at: string
          id: string
          name: string
          organization_id: string
          tax_id: string | null
          unit_type: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          address?: Json | null
          code: string
          created_at?: string
          id?: string
          name: string
          organization_id: string
          tax_id?: string | null
          unit_type: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          address?: Json | null
          code?: string
          created_at?: string
          id?: string
          name?: string
          organization_id?: string
          tax_id?: string | null
          unit_type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_units_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          legal_name: string | null
          name: string
          slug: string
          status: string
          tax_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          legal_name?: string | null
          name: string
          slug: string
          status?: string
          tax_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          legal_name?: string | null
          name?: string
          slug?: string
          status?: string
          tax_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      partner_products: {
        Row: {
          created_at: string
          partner_id: string
          product_id: string
        }
        Insert: {
          created_at?: string
          partner_id: string
          product_id: string
        }
        Update: {
          created_at?: string
          partner_id?: string
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_products_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partner_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_users: {
        Row: {
          created_at: string
          partner_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          partner_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          partner_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_users_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      partners: {
        Row: {
          accent_color: string | null
          active: boolean
          banner_url: string | null
          contact_email: string | null
          created_at: string
          facebook_url: string | null
          id: string
          instagram_url: string | null
          logo_url: string | null
          name: string
          organization_id: string
          primary_color: string | null
          slug: string
          tagline: string | null
          updated_at: string
          youtube_url: string | null
        }
        Insert: {
          accent_color?: string | null
          active?: boolean
          banner_url?: string | null
          contact_email?: string | null
          created_at?: string
          facebook_url?: string | null
          id?: string
          instagram_url?: string | null
          logo_url?: string | null
          name: string
          organization_id: string
          primary_color?: string | null
          slug: string
          tagline?: string | null
          updated_at?: string
          youtube_url?: string | null
        }
        Update: {
          accent_color?: string | null
          active?: boolean
          banner_url?: string | null
          contact_email?: string | null
          created_at?: string
          facebook_url?: string | null
          id?: string
          instagram_url?: string | null
          logo_url?: string | null
          name?: string
          organization_id?: string
          primary_color?: string | null
          slug?: string
          tagline?: string | null
          updated_at?: string
          youtube_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "partners_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount_cents: number
          approved_at: string | null
          created_at: string
          expires_at: string | null
          external_id: string | null
          id: string
          idempotency_key: string
          method: string
          order_id: string
          organization_id: string
          provider: string
          provider_metadata: Json | null
          status: string
          updated_at: string
        }
        Insert: {
          amount_cents: number
          approved_at?: string | null
          created_at?: string
          expires_at?: string | null
          external_id?: string | null
          id?: string
          idempotency_key: string
          method: string
          order_id: string
          organization_id: string
          provider: string
          provider_metadata?: Json | null
          status?: string
          updated_at?: string
        }
        Update: {
          amount_cents?: number
          approved_at?: string | null
          created_at?: string
          expires_at?: string | null
          external_id?: string | null
          id?: string
          idempotency_key?: string
          method?: string
          order_id?: string
          organization_id?: string
          provider?: string
          provider_metadata?: Json | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      permissions: {
        Row: {
          code: string
          description: string | null
          id: string
          name: string
        }
        Insert: {
          code: string
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          code?: string
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      product_images: {
        Row: {
          alt_text: string
          created_at: string
          id: string
          is_primary: boolean
          product_id: string
          sort_order: number
          storage_path: string
          variant_id: string | null
        }
        Insert: {
          alt_text: string
          created_at?: string
          id?: string
          is_primary?: boolean
          product_id: string
          sort_order?: number
          storage_path: string
          variant_id?: string | null
        }
        Update: {
          alt_text?: string
          created_at?: string
          id?: string
          is_primary?: boolean
          product_id?: string
          sort_order?: number
          storage_path?: string
          variant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_images_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      product_variants: {
        Row: {
          active: boolean
          cest: string | null
          color: string | null
          compare_at_price_cents: number | null
          cost_cents: number
          created_at: string
          ean: string | null
          fiscal_origin: string | null
          height_cm: number
          id: string
          length_cm: number
          low_stock_threshold: number | null
          name: string | null
          ncm: string | null
          price_cents: number
          product_id: string
          size: string | null
          sku: string
          updated_at: string
          weight_grams: number
          width_cm: number
        }
        Insert: {
          active?: boolean
          cest?: string | null
          color?: string | null
          compare_at_price_cents?: number | null
          cost_cents?: number
          created_at?: string
          ean?: string | null
          fiscal_origin?: string | null
          height_cm?: number
          id?: string
          length_cm?: number
          low_stock_threshold?: number | null
          name?: string | null
          ncm?: string | null
          price_cents: number
          product_id: string
          size?: string | null
          sku: string
          updated_at?: string
          weight_grams?: number
          width_cm?: number
        }
        Update: {
          active?: boolean
          cest?: string | null
          color?: string | null
          compare_at_price_cents?: number | null
          cost_cents?: number
          created_at?: string
          ean?: string | null
          fiscal_origin?: string | null
          height_cm?: number
          id?: string
          length_cm?: number
          low_stock_threshold?: number | null
          name?: string | null
          ncm?: string | null
          price_cents?: number
          product_id?: string
          size?: string | null
          sku?: string
          updated_at?: string
          weight_grams?: number
          width_cm?: number
        }
        Relationships: [
          {
            foreignKeyName: "product_variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_placements: {
        Row: {
          created_at: string
          id: string
          partner_id: string | null
          product_id: string
          section: string
        }
        Insert: {
          created_at?: string
          id?: string
          partner_id?: string | null
          product_id: string
          section: string
        }
        Update: {
          created_at?: string
          id?: string
          partner_id?: string | null
          product_id?: string
          section?: string
        }
        Relationships: []
      }
      products: {
        Row: {
          brand_id: string | null
          created_at: string
          description: string | null
          gender: string | null
          home_sections: string[]
          id: string
          name: string
          organization_id: string
          partner_id: string | null
          primary_category_id: string | null
          published_at: string | null
          search_text: unknown
          seo_description: string | null
          seo_title: string | null
          short_description: string | null
          show_in_main: boolean
          slug: string
          sport_id: string | null
          status: string
          updated_at: string
        }
        Insert: {
          brand_id?: string | null
          created_at?: string
          description?: string | null
          gender?: string | null
          home_sections?: string[]
          id?: string
          name: string
          organization_id: string
          partner_id?: string | null
          primary_category_id?: string | null
          published_at?: string | null
          search_text?: unknown
          seo_description?: string | null
          seo_title?: string | null
          short_description?: string | null
          show_in_main?: boolean
          slug: string
          sport_id?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          brand_id?: string | null
          created_at?: string
          description?: string | null
          gender?: string | null
          home_sections?: string[]
          id?: string
          name?: string
          organization_id?: string
          partner_id?: string | null
          primary_category_id?: string | null
          published_at?: string | null
          search_text?: unknown
          seo_description?: string | null
          seo_title?: string | null
          short_description?: string | null
          show_in_main?: boolean
          slug?: string
          sport_id?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_primary_category_id_fkey"
            columns: ["primary_category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_sport_id_fkey"
            columns: ["sport_id"]
            isOneToOne: false
            referencedRelation: "sports"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_path: string | null
          created_at: string
          full_name: string | null
          id: string
          organization_id: string | null
          phone: string | null
          status: string
          updated_at: string
        }
        Insert: {
          avatar_path?: string | null
          created_at?: string
          full_name?: string | null
          id: string
          organization_id?: string | null
          phone?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          avatar_path?: string | null
          created_at?: string
          full_name?: string | null
          id?: string
          organization_id?: string | null
          phone?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_order_items: {
        Row: {
          created_at: string
          id: string
          ordered_quantity: number
          purchase_order_id: string
          received_quantity: number
          total_cents: number
          unit_cost_cents: number
          variant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          ordered_quantity: number
          purchase_order_id: string
          received_quantity?: number
          total_cents: number
          unit_cost_cents: number
          variant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          ordered_quantity?: number
          purchase_order_id?: string
          received_quantity?: number
          total_cents?: number
          unit_cost_cents?: number
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_order_items_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_orders: {
        Row: {
          approved_by: string | null
          created_at: string
          created_by: string | null
          discount_cents: number
          expected_at: string | null
          freight_cents: number
          id: string
          notes: string | null
          organization_id: string
          po_number: string
          status: string
          subtotal_cents: number
          supplier_id: string
          total_cents: number
          updated_at: string
          warehouse_id: string
        }
        Insert: {
          approved_by?: string | null
          created_at?: string
          created_by?: string | null
          discount_cents?: number
          expected_at?: string | null
          freight_cents?: number
          id?: string
          notes?: string | null
          organization_id: string
          po_number: string
          status?: string
          subtotal_cents?: number
          supplier_id: string
          total_cents?: number
          updated_at?: string
          warehouse_id: string
        }
        Update: {
          approved_by?: string | null
          created_at?: string
          created_by?: string | null
          discount_cents?: number
          expected_at?: string | null
          freight_cents?: number
          id?: string
          notes?: string | null
          organization_id?: string
          po_number?: string
          status?: string
          subtotal_cents?: number
          supplier_id?: string
          total_cents?: number
          updated_at?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_orders_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      refunds: {
        Row: {
          amount_cents: number
          created_at: string
          external_id: string | null
          id: string
          idempotency_key: string
          payment_id: string
          reason: string
          requested_by: string | null
          status: string
          updated_at: string
        }
        Insert: {
          amount_cents: number
          created_at?: string
          external_id?: string | null
          id?: string
          idempotency_key: string
          payment_id: string
          reason: string
          requested_by?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          amount_cents?: number
          created_at?: string
          external_id?: string | null
          id?: string
          idempotency_key?: string
          payment_id?: string
          reason?: string
          requested_by?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "refunds_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "refunds_requested_by_fkey"
            columns: ["requested_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      return_items: {
        Row: {
          condition: string | null
          created_at: string
          id: string
          notes: string | null
          order_item_id: string
          quantity: number
          resolution: string | null
          return_id: string
        }
        Insert: {
          condition?: string | null
          created_at?: string
          id?: string
          notes?: string | null
          order_item_id: string
          quantity: number
          resolution?: string | null
          return_id: string
        }
        Update: {
          condition?: string | null
          created_at?: string
          id?: string
          notes?: string | null
          order_item_id?: string
          quantity?: number
          resolution?: string | null
          return_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "return_items_order_item_id_fkey"
            columns: ["order_item_id"]
            isOneToOne: false
            referencedRelation: "order_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "return_items_return_id_fkey"
            columns: ["return_id"]
            isOneToOne: false
            referencedRelation: "returns"
            referencedColumns: ["id"]
          },
        ]
      }
      returns: {
        Row: {
          approved_at: string | null
          completed_at: string | null
          created_at: string
          customer_id: string | null
          id: string
          order_id: string
          organization_id: string
          reason: string
          received_at: string | null
          requested_at: string
          return_number: string
          return_type: string
          status: string
          updated_at: string
        }
        Insert: {
          approved_at?: string | null
          completed_at?: string | null
          created_at?: string
          customer_id?: string | null
          id?: string
          order_id: string
          organization_id: string
          reason: string
          received_at?: string | null
          requested_at?: string
          return_number: string
          return_type: string
          status?: string
          updated_at?: string
        }
        Update: {
          approved_at?: string | null
          completed_at?: string | null
          created_at?: string
          customer_id?: string | null
          id?: string
          order_id?: string
          organization_id?: string
          reason?: string
          received_at?: string | null
          requested_at?: string
          return_number?: string
          return_type?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "returns_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "returns_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "returns_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      role_permissions: {
        Row: {
          permission_id: string
          role_id: string
        }
        Insert: {
          permission_id: string
          role_id: string
        }
        Update: {
          permission_id?: string
          role_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_permissions_permission_id_fkey"
            columns: ["permission_id"]
            isOneToOne: false
            referencedRelation: "permissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "role_permissions_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      roles: {
        Row: {
          code: string
          created_at: string
          description: string | null
          id: string
          is_system: boolean
          name: string
          organization_id: string | null
        }
        Insert: {
          code: string
          created_at?: string
          description?: string | null
          id?: string
          is_system?: boolean
          name: string
          organization_id?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          description?: string | null
          id?: string
          is_system?: boolean
          name?: string
          organization_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "roles_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      search_no_results: {
        Row: {
          created_at: string
          id: string
          results_count: number
          term: string
        }
        Insert: {
          created_at?: string
          id?: string
          results_count?: number
          term: string
        }
        Update: {
          created_at?: string
          id?: string
          results_count?: number
          term?: string
        }
        Relationships: []
      }
      shipment_events: {
        Row: {
          created_at: string
          description: string | null
          external_event_id: string | null
          id: string
          location: string | null
          occurred_at: string
          raw_payload: Json | null
          shipment_id: string
          status: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          external_event_id?: string | null
          id?: string
          location?: string | null
          occurred_at: string
          raw_payload?: Json | null
          shipment_id: string
          status: string
        }
        Update: {
          created_at?: string
          description?: string | null
          external_event_id?: string | null
          id?: string
          location?: string | null
          occurred_at?: string
          raw_payload?: Json | null
          shipment_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipment_events_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
        ]
      }
      shipments: {
        Row: {
          actual_cost_cents: number | null
          charged_to_customer_cents: number
          created_at: string
          delivered_at: string | null
          estimated_delivery_date: string | null
          external_id: string | null
          id: string
          label_storage_path: string | null
          order_id: string
          organization_id: string
          provider: string | null
          service_code: string | null
          service_name: string | null
          shipped_at: string | null
          status: string
          tracking_code: string | null
          updated_at: string
          warehouse_id: string
        }
        Insert: {
          actual_cost_cents?: number | null
          charged_to_customer_cents?: number
          created_at?: string
          delivered_at?: string | null
          estimated_delivery_date?: string | null
          external_id?: string | null
          id?: string
          label_storage_path?: string | null
          order_id: string
          organization_id: string
          provider?: string | null
          service_code?: string | null
          service_name?: string | null
          shipped_at?: string | null
          status?: string
          tracking_code?: string | null
          updated_at?: string
          warehouse_id: string
        }
        Update: {
          actual_cost_cents?: number | null
          charged_to_customer_cents?: number
          created_at?: string
          delivered_at?: string | null
          estimated_delivery_date?: string | null
          external_id?: string | null
          id?: string
          label_storage_path?: string | null
          order_id?: string
          organization_id?: string
          provider?: string | null
          service_code?: string | null
          service_name?: string | null
          shipped_at?: string | null
          status?: string
          tracking_code?: string | null
          updated_at?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shipments_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shipments_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      sports: {
        Row: {
          active: boolean
          created_at: string
          id: string
          name: string
          organization_id: string
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          name: string
          organization_id: string
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          name?: string
          organization_id?: string
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sports_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      suppliers: {
        Row: {
          active: boolean
          address: Json | null
          created_at: string
          email: string | null
          id: string
          legal_name: string
          organization_id: string
          phone: string | null
          tax_id: string | null
          trade_name: string | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          address?: Json | null
          created_at?: string
          email?: string | null
          id?: string
          legal_name: string
          organization_id: string
          phone?: string | null
          tax_id?: string | null
          trade_name?: string | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          address?: Json | null
          created_at?: string
          email?: string | null
          id?: string
          legal_name?: string
          organization_id?: string
          phone?: string | null
          tax_id?: string | null
          trade_name?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "suppliers_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          created_at: string
          role_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          role_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          role_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouses: {
        Row: {
          active: boolean
          code: string
          created_at: string
          id: string
          name: string
          organization_id: string
          unit_id: string | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          id?: string
          name: string
          organization_id: string
          unit_id?: string | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          id?: string
          name?: string
          organization_id?: string
          unit_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "warehouses_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouses_unit_id_fkey"
            columns: ["unit_id"]
            isOneToOne: false
            referencedRelation: "organization_units"
            referencedColumns: ["id"]
          },
        ]
      }
      webhook_events: {
        Row: {
          attempts: number
          event_type: string | null
          external_event_id: string
          id: string
          last_error: string | null
          payload_hash: string | null
          payload_redacted: Json | null
          processed_at: string | null
          provider: string
          received_at: string
          status: string
        }
        Insert: {
          attempts?: number
          event_type?: string | null
          external_event_id: string
          id?: string
          last_error?: string | null
          payload_hash?: string | null
          payload_redacted?: Json | null
          processed_at?: string | null
          provider: string
          received_at?: string
          status?: string
        }
        Update: {
          attempts?: number
          event_type?: string | null
          external_event_id?: string
          id?: string
          last_error?: string | null
          payload_hash?: string | null
          payload_redacted?: Json | null
          processed_at?: string | null
          provider?: string
          received_at?: string
          status?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_user_permissions: {
        Args: never
        Returns: {
          code: string
        }[]
      }
      grant_role_by_email: {
        Args: { role_code: string; target_email: string }
        Returns: undefined
      }
      search_products: {
        Args: { limit_count?: number; offset_count?: number; q?: string }
        Returns: {
          brand_id: string | null
          created_at: string
          description: string | null
          gender: string | null
          id: string
          name: string
          organization_id: string
          partner_id: string | null
          primary_category_id: string | null
          published_at: string | null
          search_text: unknown
          seo_description: string | null
          seo_title: string | null
          short_description: string | null
          slug: string
          sport_id: string | null
          status: string
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "products"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
